language: ruby
bundler_args: 
rvm:
- 1.9.2
- 1.9.3
addons:
  code_climate:
    repo_token: 66f413f9c50c6bc2d265e217df307f5de8bf36d8ad97feffb76b0174e9f9acd5
deploy:
  provider: rubygems
  api_key:
    secure: WLQzsGZ6aPzqsyS1Mu4YCZjer4ZXRFQo5j1XPkTdR/bYmip2GBQAoVIUihlIXrcTSDKRk4VVZ62GkVSOkTA41vAVvD69ARGNIgwSDzLfoVp7RWEIi7peUBdYhzOoQM8eFnOKa3UeZbEqjolsTjtQfMQISNCeL9TCmdRcyLa/avk=
  gem: mkspec
  on:
    tags: true
    repo: ritchiey/mkspec
